version: 2
updates:
  # Next.js dashboard
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Node.js server
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
