// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: heimdallv2/sidetxs/vote_ext.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { MilestoneProposition } from "./milestone";

export const protobufPackage = "heimdallv2.sidetxs";

/** Vote represents a validator's decision on a side transaction. */
export enum Vote {
  /** UNSPECIFIED - Invalid/unset vote */
  UNSPECIFIED = 0,
  /** VOTE_YES - Validator approves the side transaction */
  VOTE_YES = 1,
  /** VOTE_NO - Validator rejects the side transaction */
  VOTE_NO = 2,
  UNRECOGNIZED = -1,
}

export function voteFromJSON(object: any): Vote {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return Vote.UNSPECIFIED;
    case 1:
    case "VOTE_YES":
      return Vote.VOTE_YES;
    case 2:
    case "VOTE_NO":
      return Vote.VOTE_NO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Vote.UNRECOGNIZED;
  }
}

export function voteToJSON(object: Vote): string {
  switch (object) {
    case Vote.UNSPECIFIED:
      return "UNSPECIFIED";
    case Vote.VOTE_YES:
      return "VOTE_YES";
    case Vote.VOTE_NO:
      return "VOTE_NO";
    case Vote.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * VoteExtension contains additional data included by validators in their votes.
 * Introduced in ABCI++, vote extensions allow validators to include
 * supplementary information like milestone propositions and side transaction
 * results.
 */
export interface VoteExtension {
  /** Hash of the block this vote extension is for. */
  blockHash: Uint8Array;
  /** Height of the block this vote extension is for. */
  height: number;
  /** Results of side transaction validation by this validator. */
  sideTxResponses: SideTxResponse[];
  /** Milestone proposition submitted by this validator. */
  milestoneProposition: MilestoneProposition | undefined;
}

/** SideTxResponse contains a validator's vote on a side transaction. */
export interface SideTxResponse {
  /** Hash of the side transaction being voted on. */
  txHash: Uint8Array;
  /** The validator's vote (yes or no). */
  result: Vote;
}

function createBaseVoteExtension(): VoteExtension {
  return { blockHash: new Uint8Array(0), height: 0, sideTxResponses: [], milestoneProposition: undefined };
}

export const VoteExtension: MessageFns<VoteExtension> = {
  encode(message: VoteExtension, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockHash.length !== 0) {
      writer.uint32(10).bytes(message.blockHash);
    }
    if (message.height !== 0) {
      writer.uint32(16).int64(message.height);
    }
    for (const v of message.sideTxResponses) {
      SideTxResponse.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.milestoneProposition !== undefined) {
      MilestoneProposition.encode(message.milestoneProposition, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VoteExtension {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoteExtension();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.blockHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.height = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sideTxResponses.push(SideTxResponse.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.milestoneProposition = MilestoneProposition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VoteExtension {
    return {
      blockHash: isSet(object.blockHash)
        ? bytesFromBase64(object.blockHash)
        : isSet(object.block_hash)
          ? bytesFromBase64(object.block_hash)
          : new Uint8Array(0),
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      sideTxResponses: globalThis.Array.isArray(object?.sideTxResponses)
        ? object.sideTxResponses.map((e: any) => SideTxResponse.fromJSON(e))
        : globalThis.Array.isArray(object?.side_tx_responses)
          ? object.side_tx_responses.map((e: any) => SideTxResponse.fromJSON(e))
          : [],
      milestoneProposition: isSet(object.milestoneProposition)
        ? MilestoneProposition.fromJSON(object.milestoneProposition)
        : isSet(object.milestone_proposition)
          ? MilestoneProposition.fromJSON(object.milestone_proposition)
          : undefined,
    };
  },

  toJSON(message: VoteExtension): unknown {
    const obj: any = {};
    if (message.blockHash.length !== 0) {
      obj.blockHash = base64FromBytes(message.blockHash);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.sideTxResponses?.length) {
      obj.sideTxResponses = message.sideTxResponses.map((e) => SideTxResponse.toJSON(e));
    }
    if (message.milestoneProposition !== undefined) {
      obj.milestoneProposition = MilestoneProposition.toJSON(message.milestoneProposition);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VoteExtension>, I>>(base?: I): VoteExtension {
    return VoteExtension.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoteExtension>, I>>(object: I): VoteExtension {
    const message = createBaseVoteExtension();
    message.blockHash = object.blockHash ?? new Uint8Array(0);
    message.height = object.height ?? 0;
    message.sideTxResponses = object.sideTxResponses?.map((e) => SideTxResponse.fromPartial(e)) || [];
    message.milestoneProposition = (object.milestoneProposition !== undefined && object.milestoneProposition !== null)
      ? MilestoneProposition.fromPartial(object.milestoneProposition)
      : undefined;
    return message;
  },
};

function createBaseSideTxResponse(): SideTxResponse {
  return { txHash: new Uint8Array(0), result: 0 };
}

export const SideTxResponse: MessageFns<SideTxResponse> = {
  encode(message: SideTxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txHash.length !== 0) {
      writer.uint32(10).bytes(message.txHash);
    }
    if (message.result !== 0) {
      writer.uint32(16).int32(message.result);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SideTxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSideTxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.result = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SideTxResponse {
    return {
      txHash: isSet(object.txHash)
        ? bytesFromBase64(object.txHash)
        : isSet(object.tx_hash)
          ? bytesFromBase64(object.tx_hash)
          : new Uint8Array(0),
      result: isSet(object.result) ? voteFromJSON(object.result) : 0,
    };
  },

  toJSON(message: SideTxResponse): unknown {
    const obj: any = {};
    if (message.txHash.length !== 0) {
      obj.txHash = base64FromBytes(message.txHash);
    }
    if (message.result !== 0) {
      obj.result = voteToJSON(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SideTxResponse>, I>>(base?: I): SideTxResponse {
    return SideTxResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SideTxResponse>, I>>(object: I): SideTxResponse {
    const message = createBaseSideTxResponse();
    message.txHash = object.txHash ?? new Uint8Array(0);
    message.result = object.result ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
