// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: heimdallv2/checkpoint/checkpoint.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Duration } from "../../google/protobuf/duration";

export const protobufPackage = "heimdallv2.checkpoint";

/**
 * Checkpoint represents a snapshot of the Bor chain state at a specific block
 * range. Checkpoints are periodically submitted to the root chain (Ethereum) to
 * finalize the Bor chain state and enable fraud proofs.
 */
export interface Checkpoint {
  /** Unique sequential identifier for this checkpoint. */
  id: number;
  /** Address of the validator who proposed this checkpoint. */
  proposer: string;
  /** First block number included in this checkpoint (inclusive). */
  startBlock: number;
  /** Last block number included in this checkpoint (inclusive). */
  endBlock: number;
  /**
   * Merkle root hash of all blocks in this checkpoint range.
   * This is the primary state commitment submitted to the root chain.
   */
  rootHash: Uint8Array;
  /** Chain ID of the Bor chain this checkpoint applies to. */
  borChainId: string;
  /** Unix timestamp when this checkpoint was created. */
  timestamp: number;
}

/** Params defines the parameters for the checkpoint module. */
export interface Params {
  /**
   * Time buffer before a checkpoint can be finalized.
   * This allows validators time to submit acks or no-acks.
   */
  checkpointBufferTime:
    | Duration
    | undefined;
  /** Target number of blocks to include in each checkpoint. */
  avgCheckpointLength: number;
  /** Maximum number of blocks allowed in a single checkpoint. */
  maxCheckpointLength: number;
  /** Average time between blocks on the child (Bor) chain in seconds. */
  childChainBlockInterval: number;
}

function createBaseCheckpoint(): Checkpoint {
  return { id: 0, proposer: "", startBlock: 0, endBlock: 0, rootHash: new Uint8Array(0), borChainId: "", timestamp: 0 };
}

export const Checkpoint: MessageFns<Checkpoint> = {
  encode(message: Checkpoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.proposer !== "") {
      writer.uint32(18).string(message.proposer);
    }
    if (message.startBlock !== 0) {
      writer.uint32(24).uint64(message.startBlock);
    }
    if (message.endBlock !== 0) {
      writer.uint32(32).uint64(message.endBlock);
    }
    if (message.rootHash.length !== 0) {
      writer.uint32(42).bytes(message.rootHash);
    }
    if (message.borChainId !== "") {
      writer.uint32(50).string(message.borChainId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(56).uint64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Checkpoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckpoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.proposer = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.startBlock = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.endBlock = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.rootHash = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.borChainId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Checkpoint {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      proposer: isSet(object.proposer) ? globalThis.String(object.proposer) : "",
      startBlock: isSet(object.startBlock)
        ? globalThis.Number(object.startBlock)
        : isSet(object.start_block)
        ? globalThis.Number(object.start_block)
        : 0,
      endBlock: isSet(object.endBlock)
        ? globalThis.Number(object.endBlock)
        : isSet(object.end_block)
        ? globalThis.Number(object.end_block)
        : 0,
      rootHash: isSet(object.rootHash)
        ? bytesFromBase64(object.rootHash)
        : isSet(object.root_hash)
        ? bytesFromBase64(object.root_hash)
        : new Uint8Array(0),
      borChainId: isSet(object.borChainId)
        ? globalThis.String(object.borChainId)
        : isSet(object.bor_chain_id)
        ? globalThis.String(object.bor_chain_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: Checkpoint): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.proposer !== "") {
      obj.proposer = message.proposer;
    }
    if (message.startBlock !== 0) {
      obj.startBlock = Math.round(message.startBlock);
    }
    if (message.endBlock !== 0) {
      obj.endBlock = Math.round(message.endBlock);
    }
    if (message.rootHash.length !== 0) {
      obj.rootHash = base64FromBytes(message.rootHash);
    }
    if (message.borChainId !== "") {
      obj.borChainId = message.borChainId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Checkpoint>, I>>(base?: I): Checkpoint {
    return Checkpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Checkpoint>, I>>(object: I): Checkpoint {
    const message = createBaseCheckpoint();
    message.id = object.id ?? 0;
    message.proposer = object.proposer ?? "";
    message.startBlock = object.startBlock ?? 0;
    message.endBlock = object.endBlock ?? 0;
    message.rootHash = object.rootHash ?? new Uint8Array(0);
    message.borChainId = object.borChainId ?? "";
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseParams(): Params {
  return {
    checkpointBufferTime: undefined,
    avgCheckpointLength: 0,
    maxCheckpointLength: 0,
    childChainBlockInterval: 0,
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.checkpointBufferTime !== undefined) {
      Duration.encode(message.checkpointBufferTime, writer.uint32(10).fork()).join();
    }
    if (message.avgCheckpointLength !== 0) {
      writer.uint32(16).uint64(message.avgCheckpointLength);
    }
    if (message.maxCheckpointLength !== 0) {
      writer.uint32(24).uint64(message.maxCheckpointLength);
    }
    if (message.childChainBlockInterval !== 0) {
      writer.uint32(32).uint64(message.childChainBlockInterval);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.checkpointBufferTime = Duration.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.avgCheckpointLength = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxCheckpointLength = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.childChainBlockInterval = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      checkpointBufferTime: isSet(object.checkpointBufferTime)
        ? Duration.fromJSON(object.checkpointBufferTime)
        : isSet(object.checkpoint_buffer_time)
        ? Duration.fromJSON(object.checkpoint_buffer_time)
        : undefined,
      avgCheckpointLength: isSet(object.avgCheckpointLength)
        ? globalThis.Number(object.avgCheckpointLength)
        : isSet(object.avg_checkpoint_length)
        ? globalThis.Number(object.avg_checkpoint_length)
        : 0,
      maxCheckpointLength: isSet(object.maxCheckpointLength)
        ? globalThis.Number(object.maxCheckpointLength)
        : isSet(object.max_checkpoint_length)
        ? globalThis.Number(object.max_checkpoint_length)
        : 0,
      childChainBlockInterval: isSet(object.childChainBlockInterval)
        ? globalThis.Number(object.childChainBlockInterval)
        : isSet(object.child_chain_block_interval)
        ? globalThis.Number(object.child_chain_block_interval)
        : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.checkpointBufferTime !== undefined) {
      obj.checkpointBufferTime = Duration.toJSON(message.checkpointBufferTime);
    }
    if (message.avgCheckpointLength !== 0) {
      obj.avgCheckpointLength = Math.round(message.avgCheckpointLength);
    }
    if (message.maxCheckpointLength !== 0) {
      obj.maxCheckpointLength = Math.round(message.maxCheckpointLength);
    }
    if (message.childChainBlockInterval !== 0) {
      obj.childChainBlockInterval = Math.round(message.childChainBlockInterval);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.checkpointBufferTime = (object.checkpointBufferTime !== undefined && object.checkpointBufferTime !== null)
      ? Duration.fromPartial(object.checkpointBufferTime)
      : undefined;
    message.avgCheckpointLength = object.avgCheckpointLength ?? 0;
    message.maxCheckpointLength = object.maxCheckpointLength ?? 0;
    message.childChainBlockInterval = object.childChainBlockInterval ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
