// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: heimdallv2/checkpoint/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./checkpoint";

export const protobufPackage = "heimdallv2.checkpoint";

/** MsgCheckpoint defines the message for proposing a new checkpoint. */
export interface MsgCheckpoint {
  /** Address of the validator proposing this checkpoint. */
  proposer: string;
  /** First block number included in this checkpoint. */
  startBlock: number;
  /** Last block number included in this checkpoint. */
  endBlock: number;
  /** Merkle root hash of all blocks in the checkpoint range. */
  rootHash: Uint8Array;
  /** Merkle root hash of all account states in the checkpoint range. */
  accountRootHash: Uint8Array;
  /** Chain ID of the Bor chain. */
  borChainId: string;
}

/** MsgCheckpointResponse defines the response for MsgCheckpoint. */
export interface MsgCheckpointResponse {
}

/**
 * MsgCpAck defines the message for acknowledging a checkpoint.
 * Validators send acks to indicate they agree with a proposed checkpoint.
 */
export interface MsgCpAck {
  /** Address of the validator sending the acknowledgment. */
  from: string;
  /** Checkpoint ID being acknowledged. */
  number: number;
  /** Address of the checkpoint proposer. */
  proposer: string;
  /** First block number in the checkpoint. */
  startBlock: number;
  /** Last block number in the checkpoint. */
  endBlock: number;
  /** Root hash of the checkpoint being acknowledged. */
  rootHash: Uint8Array;
}

/** MsgCpAckResponse defines the response for MsgCpAck. */
export interface MsgCpAckResponse {
}

/**
 * MsgCpNoAck defines the message for rejecting a checkpoint.
 * Validators send no-acks to indicate they disagree with a proposed checkpoint.
 */
export interface MsgCpNoAck {
  /** Address of the validator sending the rejection. */
  from: string;
}

/** MsgCheckpointNoAckResponse defines the response for MsgCpNoAck. */
export interface MsgCheckpointNoAckResponse {
}

/**
 * MsgUpdateParams defines the message for updating checkpoint module
 * parameters.
 */
export interface MsgUpdateParams {
  /** Address of the governance authority (typically the governance module). */
  authority: string;
  /** New parameters to set. */
  params: Params | undefined;
}

/** MsgUpdateParamsResponse defines the response for MsgUpdateParams. */
export interface MsgUpdateParamsResponse {
}

function createBaseMsgCheckpoint(): MsgCheckpoint {
  return {
    proposer: "",
    startBlock: 0,
    endBlock: 0,
    rootHash: new Uint8Array(0),
    accountRootHash: new Uint8Array(0),
    borChainId: "",
  };
}

export const MsgCheckpoint: MessageFns<MsgCheckpoint> = {
  encode(message: MsgCheckpoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proposer !== "") {
      writer.uint32(10).string(message.proposer);
    }
    if (message.startBlock !== 0) {
      writer.uint32(16).uint64(message.startBlock);
    }
    if (message.endBlock !== 0) {
      writer.uint32(24).uint64(message.endBlock);
    }
    if (message.rootHash.length !== 0) {
      writer.uint32(34).bytes(message.rootHash);
    }
    if (message.accountRootHash.length !== 0) {
      writer.uint32(42).bytes(message.accountRootHash);
    }
    if (message.borChainId !== "") {
      writer.uint32(50).string(message.borChainId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCheckpoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCheckpoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.proposer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.startBlock = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.endBlock = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.rootHash = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.accountRootHash = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.borChainId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCheckpoint {
    return {
      proposer: isSet(object.proposer) ? globalThis.String(object.proposer) : "",
      startBlock: isSet(object.startBlock)
        ? globalThis.Number(object.startBlock)
        : isSet(object.start_block)
        ? globalThis.Number(object.start_block)
        : 0,
      endBlock: isSet(object.endBlock)
        ? globalThis.Number(object.endBlock)
        : isSet(object.end_block)
        ? globalThis.Number(object.end_block)
        : 0,
      rootHash: isSet(object.rootHash)
        ? bytesFromBase64(object.rootHash)
        : isSet(object.root_hash)
        ? bytesFromBase64(object.root_hash)
        : new Uint8Array(0),
      accountRootHash: isSet(object.accountRootHash)
        ? bytesFromBase64(object.accountRootHash)
        : isSet(object.account_root_hash)
        ? bytesFromBase64(object.account_root_hash)
        : new Uint8Array(0),
      borChainId: isSet(object.borChainId)
        ? globalThis.String(object.borChainId)
        : isSet(object.bor_chain_id)
        ? globalThis.String(object.bor_chain_id)
        : "",
    };
  },

  toJSON(message: MsgCheckpoint): unknown {
    const obj: any = {};
    if (message.proposer !== "") {
      obj.proposer = message.proposer;
    }
    if (message.startBlock !== 0) {
      obj.startBlock = Math.round(message.startBlock);
    }
    if (message.endBlock !== 0) {
      obj.endBlock = Math.round(message.endBlock);
    }
    if (message.rootHash.length !== 0) {
      obj.rootHash = base64FromBytes(message.rootHash);
    }
    if (message.accountRootHash.length !== 0) {
      obj.accountRootHash = base64FromBytes(message.accountRootHash);
    }
    if (message.borChainId !== "") {
      obj.borChainId = message.borChainId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCheckpoint>, I>>(base?: I): MsgCheckpoint {
    return MsgCheckpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCheckpoint>, I>>(object: I): MsgCheckpoint {
    const message = createBaseMsgCheckpoint();
    message.proposer = object.proposer ?? "";
    message.startBlock = object.startBlock ?? 0;
    message.endBlock = object.endBlock ?? 0;
    message.rootHash = object.rootHash ?? new Uint8Array(0);
    message.accountRootHash = object.accountRootHash ?? new Uint8Array(0);
    message.borChainId = object.borChainId ?? "";
    return message;
  },
};

function createBaseMsgCheckpointResponse(): MsgCheckpointResponse {
  return {};
}

export const MsgCheckpointResponse: MessageFns<MsgCheckpointResponse> = {
  encode(_: MsgCheckpointResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCheckpointResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCheckpointResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCheckpointResponse {
    return {};
  },

  toJSON(_: MsgCheckpointResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCheckpointResponse>, I>>(base?: I): MsgCheckpointResponse {
    return MsgCheckpointResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCheckpointResponse>, I>>(_: I): MsgCheckpointResponse {
    const message = createBaseMsgCheckpointResponse();
    return message;
  },
};

function createBaseMsgCpAck(): MsgCpAck {
  return { from: "", number: 0, proposer: "", startBlock: 0, endBlock: 0, rootHash: new Uint8Array(0) };
}

export const MsgCpAck: MessageFns<MsgCpAck> = {
  encode(message: MsgCpAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.number !== 0) {
      writer.uint32(16).uint64(message.number);
    }
    if (message.proposer !== "") {
      writer.uint32(26).string(message.proposer);
    }
    if (message.startBlock !== 0) {
      writer.uint32(32).uint64(message.startBlock);
    }
    if (message.endBlock !== 0) {
      writer.uint32(40).uint64(message.endBlock);
    }
    if (message.rootHash.length !== 0) {
      writer.uint32(50).bytes(message.rootHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCpAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCpAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.number = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.proposer = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.startBlock = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.endBlock = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.rootHash = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCpAck {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      number: isSet(object.number) ? globalThis.Number(object.number) : 0,
      proposer: isSet(object.proposer) ? globalThis.String(object.proposer) : "",
      startBlock: isSet(object.startBlock)
        ? globalThis.Number(object.startBlock)
        : isSet(object.start_block)
        ? globalThis.Number(object.start_block)
        : 0,
      endBlock: isSet(object.endBlock)
        ? globalThis.Number(object.endBlock)
        : isSet(object.end_block)
        ? globalThis.Number(object.end_block)
        : 0,
      rootHash: isSet(object.rootHash)
        ? bytesFromBase64(object.rootHash)
        : isSet(object.root_hash)
        ? bytesFromBase64(object.root_hash)
        : new Uint8Array(0),
    };
  },

  toJSON(message: MsgCpAck): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.number !== 0) {
      obj.number = Math.round(message.number);
    }
    if (message.proposer !== "") {
      obj.proposer = message.proposer;
    }
    if (message.startBlock !== 0) {
      obj.startBlock = Math.round(message.startBlock);
    }
    if (message.endBlock !== 0) {
      obj.endBlock = Math.round(message.endBlock);
    }
    if (message.rootHash.length !== 0) {
      obj.rootHash = base64FromBytes(message.rootHash);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCpAck>, I>>(base?: I): MsgCpAck {
    return MsgCpAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCpAck>, I>>(object: I): MsgCpAck {
    const message = createBaseMsgCpAck();
    message.from = object.from ?? "";
    message.number = object.number ?? 0;
    message.proposer = object.proposer ?? "";
    message.startBlock = object.startBlock ?? 0;
    message.endBlock = object.endBlock ?? 0;
    message.rootHash = object.rootHash ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgCpAckResponse(): MsgCpAckResponse {
  return {};
}

export const MsgCpAckResponse: MessageFns<MsgCpAckResponse> = {
  encode(_: MsgCpAckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCpAckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCpAckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCpAckResponse {
    return {};
  },

  toJSON(_: MsgCpAckResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCpAckResponse>, I>>(base?: I): MsgCpAckResponse {
    return MsgCpAckResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCpAckResponse>, I>>(_: I): MsgCpAckResponse {
    const message = createBaseMsgCpAckResponse();
    return message;
  },
};

function createBaseMsgCpNoAck(): MsgCpNoAck {
  return { from: "" };
}

export const MsgCpNoAck: MessageFns<MsgCpNoAck> = {
  encode(message: MsgCpNoAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCpNoAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCpNoAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCpNoAck {
    return { from: isSet(object.from) ? globalThis.String(object.from) : "" };
  },

  toJSON(message: MsgCpNoAck): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCpNoAck>, I>>(base?: I): MsgCpNoAck {
    return MsgCpNoAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCpNoAck>, I>>(object: I): MsgCpNoAck {
    const message = createBaseMsgCpNoAck();
    message.from = object.from ?? "";
    return message;
  },
};

function createBaseMsgCheckpointNoAckResponse(): MsgCheckpointNoAckResponse {
  return {};
}

export const MsgCheckpointNoAckResponse: MessageFns<MsgCheckpointNoAckResponse> = {
  encode(_: MsgCheckpointNoAckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCheckpointNoAckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCheckpointNoAckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCheckpointNoAckResponse {
    return {};
  },

  toJSON(_: MsgCheckpointNoAckResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCheckpointNoAckResponse>, I>>(base?: I): MsgCheckpointNoAckResponse {
    return MsgCheckpointNoAckResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCheckpointNoAckResponse>, I>>(_: I): MsgCheckpointNoAckResponse {
    const message = createBaseMsgCheckpointNoAckResponse();
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

/** Msg defines the gRPC message service for the checkpoint module. */
export interface Msg {
  /** Checkpoint defines a method for proposing a new checkpoint. */
  Checkpoint(request: MsgCheckpoint): Promise<MsgCheckpointResponse>;
  /** CheckpointAck defines a method for validators to acknowledge a checkpoint. */
  CheckpointAck(request: MsgCpAck): Promise<MsgCpAckResponse>;
  /** CheckpointNoAck defines a method for validators to reject a checkpoint. */
  CheckpointNoAck(request: MsgCpNoAck): Promise<MsgCheckpointNoAckResponse>;
  /**
   * UpdateParams defines a method for updating checkpoint module parameters.
   * Only the governance authority can execute this.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
}

export const MsgServiceName = "heimdallv2.checkpoint.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.Checkpoint = this.Checkpoint.bind(this);
    this.CheckpointAck = this.CheckpointAck.bind(this);
    this.CheckpointNoAck = this.CheckpointNoAck.bind(this);
    this.UpdateParams = this.UpdateParams.bind(this);
  }
  Checkpoint(request: MsgCheckpoint): Promise<MsgCheckpointResponse> {
    const data = MsgCheckpoint.encode(request).finish();
    const promise = this.rpc.request(this.service, "Checkpoint", data);
    return promise.then((data) => MsgCheckpointResponse.decode(new BinaryReader(data)));
  }

  CheckpointAck(request: MsgCpAck): Promise<MsgCpAckResponse> {
    const data = MsgCpAck.encode(request).finish();
    const promise = this.rpc.request(this.service, "CheckpointAck", data);
    return promise.then((data) => MsgCpAckResponse.decode(new BinaryReader(data)));
  }

  CheckpointNoAck(request: MsgCpNoAck): Promise<MsgCheckpointNoAckResponse> {
    const data = MsgCpNoAck.encode(request).finish();
    const promise = this.rpc.request(this.service, "CheckpointNoAck", data);
    return promise.then((data) => MsgCheckpointNoAckResponse.decode(new BinaryReader(data)));
  }

  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
