// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: heimdallv2/milestone/milestone.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "heimdallv2.milestone";

/**
 * Milestone represents a fast-finality checkpoint for the Bor chain.
 * Milestones provide intermediate finalization between full checkpoints,
 * allowing for quicker finality guarantees.
 */
export interface Milestone {
  /** Address of the validator who proposed this milestone. */
  proposer: string;
  /** First block number included in this milestone (inclusive). */
  startBlock: number;
  /** Last block number included in this milestone (inclusive). */
  endBlock: number;
  /** Hash of the end block in this milestone. */
  hash: Uint8Array;
  /** Chain ID of the Bor chain this milestone applies to. */
  borChainId: string;
  /** Unique identifier for this milestone (typically a hash). */
  milestoneId: string;
  /** Unix timestamp when this milestone was created. */
  timestamp: number;
  /** Total difficulty of the Bor chain at the end block. */
  totalDifficulty: number;
}

/** MilestoneCount tracks the total number of milestones. */
export interface MilestoneCount {
  /** Total number of milestones. */
  count: number;
}

/**
 * MilestoneProposition represents a proposed milestone submitted via vote
 * extensions. Validators include these in their vote extensions to propose new
 * milestones.
 */
export interface MilestoneProposition {
  /** Hashes of all blocks included in this milestone proposition. */
  blockHashes: Uint8Array[];
  /** Starting block number for this proposition. */
  startBlockNumber: number;
  /** Hash of the parent block (block before start_block_number). */
  parentHash: Uint8Array;
  /**
   * Total difficulty values for each block in the proposition.
   * Corresponds 1:1 with block_hashes.
   */
  blockTds: number[];
}

/** Params defines the parameters for the milestone module. */
export interface Params {
  /** Maximum number of blocks that can be included in a milestone proposition. */
  maxMilestonePropositionLength: number;
  /**
   * Fast-finality threshold: minimum number of validators required to agree
   * on a milestone proposition for it to be accepted.
   */
  ffMilestoneThreshold: number;
  /**
   * Fast-finality interval: target number of blocks between milestone
   * propositions.
   */
  ffMilestoneBlockInterval: number;
}

function createBaseMilestone(): Milestone {
  return {
    proposer: "",
    startBlock: 0,
    endBlock: 0,
    hash: new Uint8Array(0),
    borChainId: "",
    milestoneId: "",
    timestamp: 0,
    totalDifficulty: 0,
  };
}

export const Milestone: MessageFns<Milestone> = {
  encode(message: Milestone, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proposer !== "") {
      writer.uint32(10).string(message.proposer);
    }
    if (message.startBlock !== 0) {
      writer.uint32(16).uint64(message.startBlock);
    }
    if (message.endBlock !== 0) {
      writer.uint32(24).uint64(message.endBlock);
    }
    if (message.hash.length !== 0) {
      writer.uint32(34).bytes(message.hash);
    }
    if (message.borChainId !== "") {
      writer.uint32(42).string(message.borChainId);
    }
    if (message.milestoneId !== "") {
      writer.uint32(50).string(message.milestoneId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(56).uint64(message.timestamp);
    }
    if (message.totalDifficulty !== 0) {
      writer.uint32(64).uint64(message.totalDifficulty);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Milestone {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMilestone();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.proposer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.startBlock = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.endBlock = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.hash = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.borChainId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.milestoneId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.totalDifficulty = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Milestone {
    return {
      proposer: isSet(object.proposer) ? globalThis.String(object.proposer) : "",
      startBlock: isSet(object.startBlock)
        ? globalThis.Number(object.startBlock)
        : isSet(object.start_block)
        ? globalThis.Number(object.start_block)
        : 0,
      endBlock: isSet(object.endBlock)
        ? globalThis.Number(object.endBlock)
        : isSet(object.end_block)
        ? globalThis.Number(object.end_block)
        : 0,
      hash: isSet(object.hash) ? bytesFromBase64(object.hash) : new Uint8Array(0),
      borChainId: isSet(object.borChainId)
        ? globalThis.String(object.borChainId)
        : isSet(object.bor_chain_id)
        ? globalThis.String(object.bor_chain_id)
        : "",
      milestoneId: isSet(object.milestoneId)
        ? globalThis.String(object.milestoneId)
        : isSet(object.milestone_id)
        ? globalThis.String(object.milestone_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      totalDifficulty: isSet(object.totalDifficulty)
        ? globalThis.Number(object.totalDifficulty)
        : isSet(object.total_difficulty)
        ? globalThis.Number(object.total_difficulty)
        : 0,
    };
  },

  toJSON(message: Milestone): unknown {
    const obj: any = {};
    if (message.proposer !== "") {
      obj.proposer = message.proposer;
    }
    if (message.startBlock !== 0) {
      obj.startBlock = Math.round(message.startBlock);
    }
    if (message.endBlock !== 0) {
      obj.endBlock = Math.round(message.endBlock);
    }
    if (message.hash.length !== 0) {
      obj.hash = base64FromBytes(message.hash);
    }
    if (message.borChainId !== "") {
      obj.borChainId = message.borChainId;
    }
    if (message.milestoneId !== "") {
      obj.milestoneId = message.milestoneId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.totalDifficulty !== 0) {
      obj.totalDifficulty = Math.round(message.totalDifficulty);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Milestone>, I>>(base?: I): Milestone {
    return Milestone.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Milestone>, I>>(object: I): Milestone {
    const message = createBaseMilestone();
    message.proposer = object.proposer ?? "";
    message.startBlock = object.startBlock ?? 0;
    message.endBlock = object.endBlock ?? 0;
    message.hash = object.hash ?? new Uint8Array(0);
    message.borChainId = object.borChainId ?? "";
    message.milestoneId = object.milestoneId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.totalDifficulty = object.totalDifficulty ?? 0;
    return message;
  },
};

function createBaseMilestoneCount(): MilestoneCount {
  return { count: 0 };
}

export const MilestoneCount: MessageFns<MilestoneCount> = {
  encode(message: MilestoneCount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.count !== 0) {
      writer.uint32(8).uint64(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MilestoneCount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMilestoneCount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.count = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MilestoneCount {
    return { count: isSet(object.count) ? globalThis.Number(object.count) : 0 };
  },

  toJSON(message: MilestoneCount): unknown {
    const obj: any = {};
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MilestoneCount>, I>>(base?: I): MilestoneCount {
    return MilestoneCount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MilestoneCount>, I>>(object: I): MilestoneCount {
    const message = createBaseMilestoneCount();
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseMilestoneProposition(): MilestoneProposition {
  return { blockHashes: [], startBlockNumber: 0, parentHash: new Uint8Array(0), blockTds: [] };
}

export const MilestoneProposition: MessageFns<MilestoneProposition> = {
  encode(message: MilestoneProposition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.blockHashes) {
      writer.uint32(10).bytes(v!);
    }
    if (message.startBlockNumber !== 0) {
      writer.uint32(16).uint64(message.startBlockNumber);
    }
    if (message.parentHash.length !== 0) {
      writer.uint32(26).bytes(message.parentHash);
    }
    for (const v of message.blockTds) {
      writer.uint32(32).uint64(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MilestoneProposition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMilestoneProposition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.blockHashes.push(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.startBlockNumber = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parentHash = reader.bytes();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.blockTds.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.blockTds.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MilestoneProposition {
    return {
      blockHashes: globalThis.Array.isArray(object?.blockHashes)
        ? object.blockHashes.map((e: any) => bytesFromBase64(e))
        : globalThis.Array.isArray(object?.block_hashes)
        ? object.block_hashes.map((e: any) => bytesFromBase64(e))
        : [],
      startBlockNumber: isSet(object.startBlockNumber)
        ? globalThis.Number(object.startBlockNumber)
        : isSet(object.start_block_number)
        ? globalThis.Number(object.start_block_number)
        : 0,
      parentHash: isSet(object.parentHash)
        ? bytesFromBase64(object.parentHash)
        : isSet(object.parent_hash)
        ? bytesFromBase64(object.parent_hash)
        : new Uint8Array(0),
      blockTds: globalThis.Array.isArray(object?.blockTds)
        ? object.blockTds.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.block_tds)
        ? object.block_tds.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: MilestoneProposition): unknown {
    const obj: any = {};
    if (message.blockHashes?.length) {
      obj.blockHashes = message.blockHashes.map((e) => base64FromBytes(e));
    }
    if (message.startBlockNumber !== 0) {
      obj.startBlockNumber = Math.round(message.startBlockNumber);
    }
    if (message.parentHash.length !== 0) {
      obj.parentHash = base64FromBytes(message.parentHash);
    }
    if (message.blockTds?.length) {
      obj.blockTds = message.blockTds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MilestoneProposition>, I>>(base?: I): MilestoneProposition {
    return MilestoneProposition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MilestoneProposition>, I>>(object: I): MilestoneProposition {
    const message = createBaseMilestoneProposition();
    message.blockHashes = object.blockHashes?.map((e) => e) || [];
    message.startBlockNumber = object.startBlockNumber ?? 0;
    message.parentHash = object.parentHash ?? new Uint8Array(0);
    message.blockTds = object.blockTds?.map((e) => e) || [];
    return message;
  },
};

function createBaseParams(): Params {
  return { maxMilestonePropositionLength: 0, ffMilestoneThreshold: 0, ffMilestoneBlockInterval: 0 };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.maxMilestonePropositionLength !== 0) {
      writer.uint32(8).uint64(message.maxMilestonePropositionLength);
    }
    if (message.ffMilestoneThreshold !== 0) {
      writer.uint32(16).uint64(message.ffMilestoneThreshold);
    }
    if (message.ffMilestoneBlockInterval !== 0) {
      writer.uint32(24).uint64(message.ffMilestoneBlockInterval);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxMilestonePropositionLength = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ffMilestoneThreshold = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.ffMilestoneBlockInterval = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      maxMilestonePropositionLength: isSet(object.maxMilestonePropositionLength)
        ? globalThis.Number(object.maxMilestonePropositionLength)
        : isSet(object.max_milestone_proposition_length)
        ? globalThis.Number(object.max_milestone_proposition_length)
        : 0,
      ffMilestoneThreshold: isSet(object.ffMilestoneThreshold)
        ? globalThis.Number(object.ffMilestoneThreshold)
        : isSet(object.ff_milestone_threshold)
        ? globalThis.Number(object.ff_milestone_threshold)
        : 0,
      ffMilestoneBlockInterval: isSet(object.ffMilestoneBlockInterval)
        ? globalThis.Number(object.ffMilestoneBlockInterval)
        : isSet(object.ff_milestone_block_interval)
        ? globalThis.Number(object.ff_milestone_block_interval)
        : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.maxMilestonePropositionLength !== 0) {
      obj.maxMilestonePropositionLength = Math.round(message.maxMilestonePropositionLength);
    }
    if (message.ffMilestoneThreshold !== 0) {
      obj.ffMilestoneThreshold = Math.round(message.ffMilestoneThreshold);
    }
    if (message.ffMilestoneBlockInterval !== 0) {
      obj.ffMilestoneBlockInterval = Math.round(message.ffMilestoneBlockInterval);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.maxMilestonePropositionLength = object.maxMilestonePropositionLength ?? 0;
    message.ffMilestoneThreshold = object.ffMilestoneThreshold ?? 0;
    message.ffMilestoneBlockInterval = object.ffMilestoneBlockInterval ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
